package quantum

var words = map[string][]string{
	"nCosmos": []string{
		"cosmos",
		"quantum soup",
		"infinite",
		"universe",
		"galaxy",
		"multiverse",
		"grid",
		"quantum matrix",
		"totality",
		"quantum cycle",
		"nexus",
		"planet",
		"solar system",
		"world",
		"stratosphere",
		"dreamscape",
		"biosphere",
	},

	"nPerson": []string{
		"being",
		"child",
		"traveller",
		"entity",
		"lifeform",
		"wanderer",
		"visitor",
		"prophet",
		"seeker",
	},

	"nPersonPlural": []string{
		"beings",
		"travellers",
		"entities",
		"lifeforms",
		"dreamweavers",
		"adventurers",
		"pilgrims",
		"warriors",
		"messengers",
		"dreamers",
		"storytellers",
		"seekers",
	},

	"nMass": []string{
		"consciousness",
		"nature",
		"beauty",
		"knowledge",
		"truth",
		"life",
		"healing",
		"potential",
		"freedom",
		"purpose",
		"coherence",
		"choice",
		"passion",
		"understanding",
		"balance",
		"growth",
		"inspiration",
		"conscious living",
		"energy",
		"health",
		"spacetime",
		"learning",
		"being",
		"wisdom",
		"stardust",
		"sharing",
		"science",
		"curiosity",
		"hope",
		"wonder",
		"faith",
		"fulfillment",
		"peace",
		"rebirth",
		"self-actualization",
		"presence",
		"power",
		"will",
		"flow",
		"potential",
		"potentiality",
		"chi",
		"intuition",
		"synchronicity",
		"wellbeing",
		"joy",
		"love",
		"karma",
		"life-force",
		"awareness",
		"guidance",
		"transformation",
		"grace",
		"divinity",
		"non-locality",
		"inseparability",
		"interconnectedness",
		"transcendence",
		"empathy",
		"insight",
		"rejuvenation",
		"ecstasy",
		"aspiration",
		"complexity",
		"serenity",
	},

	"nMassBad": []string{
		"turbulence",
		"pain",
		"suffering",
		"stagnation",
		"desire",
		"bondage",
		"greed",
		"selfishness",
		"ego",
		"dogma",
		"illusion",
		"delusion",
		"yearning",
		"discontinuity",
		"materialism",
	},

	"nOurPlural": []string{
		"souls",
		"lives",
		"dreams",
		"hopes",
		"bodies",
		"hearts",
		"brains",
		"third eyes",
		"essences",
		"chakras",
	},

	"nPath": []string{
		"circuit",
		"mission",
		"journey",
		"path",
		"quest",
		"vision quest",
		"story",
		"myth",
	},

	"nOf": []string{
		"quantum leap",
		"evolution",
		"spark",
		"lightning bolt",
		"reintegration",
		"vector",
		"rebirth",
		"revolution",
		"wellspring",
		"fount",
		"source",
		"fusion",
		"canopy",
		"flow",
		"network",
		"current",
		"transmission",
		"oasis",
		"quantum shift",
		"paradigm shift",
		"metamorphosis",
		"harmonizing",
		"reimagining",
		"rekindling",
		"unifying",
		"osmosis",
		"vision",
		"uprising",
		"explosion",
	},

	"ing": []string{
		"flowering",
		"unfolding",
		"blossoming",
		"awakening",
		"deepening",
		"refining",
		"maturing",
		"evolving",
		"summoning",
		"unveiling",
		"redefining",
		"condensing",
		"ennobling",
	},

	"adj": []string{
		"enlightened",
		"zero-point",
		"quantum",
		"high-frequency",
		"Vedic",
		"non-dual",
		"conscious",
		"sentient",
		"sacred",
		"infinite",
		"primordial",
		"ancient",
		"powerful",
		"spiritual",
		"higher",
		"advanced",
		"internal",
		"sublime",
		"technological",
		"dynamic",
		"life-affirming",
		"sensual",
		"unrestricted",
		"ever-present",
		"endless",
		"ethereal",
		"astral",
		"cosmic",
		"spatial",
		"transformative",
		"unified",
		"non-local",
		"mystical",
		"divine",
		"self-aware",
		"magical",
		"amazing",
		"interstellar",
		"unlimited",
		"authentic",
		"angelic",
		"karmic",
		"psychic",
		"pranic",
		"consciousness-expanding",
		"perennial",
		"heroic",
		"archetypal",
		"mythic",
		"intergalatic",
		"holistic",
		"joyous",
		"sublime",
	},

	"adjBig": []string{
		"epic",
		"unimaginable",
		"colossal",
		"unfathomable",
		"magnificent",
		"enormous",
		"jaw-dropping",
		"ecstatic",
		"powerful",
		"untold",
		"astonishing",
		"incredible",
		"breathtaking",
		"staggering",
	},

	"adjWith": []string{
		"aglow with",
		"buzzing with",
		"beaming with",
		"full of",
		"overflowing with",
		"radiating",
		"bursting with",
		"electrified with",
	},

	"adjPrefix": []string{
		"ultra-",
		"supra-",
		"hyper-",
		"pseudo-",
	},

	"vtMass": []string{
		"inspire",
		"integrate",
		"ignite",
		"discover",
		"rediscover",
		"foster",
		"release",
		"manifest",
		"harmonize",
		"engender",
		"bring forth",
		"bring about",
		"create",
		"spark",
		"reveal",
		"generate",
		"leverage",
	},

	"vtPerson": []string{
		"enlighten",
		"inspire",
		"empower",
		"unify",
		"strengthen",
		"recreate",
		"fulfill",
		"change",
		"develop",
		"heal",
		"awaken",
		"synergize",
		"ground",
		"bless",
		"beckon",
	},

	"viPerson": []string{
		"exist",
		"believe",
		"grow",
		"live",
		"dream",
		"reflect",
		"heal",
		"vibrate",
		"self-actualize",
	},

	"vtDestroy": []string{
		"destroy",
		"eliminate",
		"shatter",
		"disrupt",
		"sabotage",
		"exterminate",
		"obliterate",
		"eradicate",
		"extinguish",
		"erase",
		"confront",
	},

	"nTheXOf": []string{
		"richness",
		"truth",
		"growth",
		"nature",
		"healing",
		"knowledge",
	},

	"ppPerson": []string{
		"awakened",
		"re-energized",
		"recreated",
		"reborn",
		"guided",
		"aligned",
	},

	"ppThingPrep": []string{
		"enveloped in",
		"transformed into",
		"nurtured by",
		"opened by",
		"immersed in",
		"engulfed in",
		"baptized in",
	},

	"fixedAdvP": []string{
		"through non-local interactions",
		"inherent in nature",
		"at the quantum level",
		"at the speed of light",
		"of unfathomable proportions",
		"on a cosmic scale",
		"devoid of self",
		"of the creative act",
	},

	"fixedAdvPPlace": []string{
		"in this dimension",
		"outside time",
		"within the Godhead",
		"at home in the cosmos",
	},

	"fixedNP": []string{
		"expanding wave functions",
		"superpositions of possibilities",
		"electromagnetic forces",
		"electromagnetic resonance",
		"molecular structures",
		"atomic ionization",
		"electrical impulses",
		"a resonance cascade",
		"bio-electricity",
		"ultrasonic energy",
		"sonar energy",
		"vibrations",
		"frequencies",
		"four-dimensional superstructures",
		"ultra-sentient particles",
		"sub-atomic particles",
		"chaos-driven reactions",
		"supercharged electrons",
		"supercharged waveforms",
		"pulses",
		"transmissions",
		"morphogenetic fields",
		"bio-feedback",
		"meridians",
		"morphic resonance",
	},

	"nSubject": []string{
		"alternative medicine",
		"astrology",
		"tarot",
		"crystal healing",
		"the akashic record",
		"feng shui",
		"acupuncture",
		"homeopathy",
		"aromatherapy",
		"ayurvedic medicine",
		"faith healing",
		"prayer",
		"astral projection",
		"Kabala",
		"reiki",
		"naturopathy",
		"numerology",
		"affirmations",
		"the Law of Attraction",
	},

	"vOpenUp": []string{
		"open up",
		"give us access to",
		"enable us to access",
		"remove the barriers to",
		"clear a path toward",
		"let us access",
		"tap into",
		"align us with",
	},

	"vTraverse": []string{
		"traverse",
		"walk",
		"follow",
		"engage with",
		"go along",
		"roam",
		"navigate",
		"wander",
		"embark on",
	},
}
